### ISSUE TITLE
Is there a way to evaluate a section? Like in QT?

### ISSUE THREAD

**Issue by chronopolis5k** [nwhetsell/ide-csound#10]

**Comment by nwhetsell** [comment]
I don’t understand the question, sorry.

**Comment by chronopolis5k** [comment]
In Csound QT you can evaluate a section of code. Is there a way to do this in Atom? Or how would one go about doing that? Sorry for my ignorance about how Atom scripts are configured.

**Comment by nwhetsell** [comment]
There’s currently no way to do this in ide-csound. I’d welcome a pull request to add this. It may be possible to do this without too much trouble, for example by passing text selected in an editor (used to [show help for opcodes](https://github.com/nwhetsell/ide-csound/blob/a3359eb95502f48fd1d40c2a35bcb9494ca07089/lib/ide-csound.coffee#L108)) to something like [what happens in the method used to run files](https://github.com/nwhetsell/ide-csound/blob/a3359eb95502f48fd1d40c2a35bcb9494ca07089/lib/ide-csound.coffee#L80).
