### ISSUE TITLE
Cant make it work on windows

### ISSUE THREAD

**Issue by pablozoani** [nwhetsell/ide-csound#9]
Hello, i am trying to install the ide-csound package for atom but i got an error.

In Powershell:

 Boost installed at:
  "C:\local\boost_1_71_0"

 Csound include at:
  "C:\Program Files\Csound6_x64\include"

 Csound Lib:
  "C:\Program Files\Csound6_x64\lib"

 Windows tools and python successfully installed:
  npm install --global --production windows-build-tools

then...
```
PS C:\WINDOWS\system32> $Env:CL = '/I"C:\local\boost_1_71_0" /I"C:\Program Files\Csound6_x64\include"'
>> $Env:LINK = '"C:\Program Files\Csound6_x64\lib"'
>> npm install csound-api                                                                                                                                                                       
> csound-api@0.10.14 install C:\WINDOWS\system32\node_modules\csound-api
> node-gyp rebuild


C:\WINDOWS\system32\node_modules\csound-api>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: El archivo de proyecto no existe.
Modificador: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\csound-api
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN system32@1.0.0 No description
npm WARN system32@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! csound-api@0.10.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csound-api@0.10.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2019-10-12T20_36_28_105Z-debug.log
```

Regards,
 Pablo

**Comment by nwhetsell** [comment]
The issue is either that the value of `$Env:LINK` is wrong (it should be `'"C:\Program Files\Csound6_x64\lib\csound64.lib"'`), or that you’re attempting to install the [csound-api](https://github.com/nwhetsell/csound-api) Node.js module in `C:\WINDOWS\system32`, or both.

Try entering in PowerShell:

```powershell
$Env:CL = '/I"C:\local\boost_1_71_0" /I"C:\Program Files\Csound6_x64\include"'
$Env:LINK = '"C:\Program Files\Csound6_x64\lib\csound64.lib"'
apm install ide-csound
```

Slightly off topic, but I’ve tried to set up AppVeyor to test this package. Unfortunately, I run into a [weird alignment error](https://ci.appveyor.com/project/nwhetsell/ide-csound#L58) when building csound-api that [doesn’t occur](https://ci.appveyor.com/project/nwhetsell/csound-api) when building that module alone on AppVeyor. I’d welcome a pull request to make AppVeyor build ide-csound.

**Comment by pablozoani** [comment]
Hello Nathan, that has resolved my issue. Do you plan to add a stop command, or is there a way to stop csound without crashing?

This seems to be very useful tool, thanks.

 Pablo

**Comment by nwhetsell** [comment]
> Hello Nathan, that has resolved my issue.

Excellent, happy to help!

> Do you plan to add a stop command…

No, unfortunately. I’d welcome a pull request to add this, and for what it’s worth I outlined a possible way to do this in https://github.com/nwhetsell/ide-csound/issues/8#issuecomment-532242326.

> …or is there a way to stop csound without crashing?

I’ve noticed Csound crashing too, and I believe this is a relatively recent issue. This is most likely an issue with Csound itself, though, not ide-csound.

> This seems to be very useful tool, thanks.

Thank you!
